linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - bodyclose
    - dupl
    - exportloopref
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - golint
    - goprintffuncname
    - gosec
    - interfacer
    - maligned
    - prealloc
    - stylecheck
    - unconvert
    - whitespace
