{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hcloud-pricing-exporter.fullname" . }}
type: Opaque
data:
  token: {{ required "An token to access the HCloud API is required" .Values.secret.token | b64enc }}
{{- end }}
