apiVersion: v2
name: hcloud-pricing-exporter
description: A prometheus exporter for the current pricing and costs of your HCloud account
home: https://github.com/jangraefen/hcloud-pricing-exporter
maintainers:
  - name: Jan Graefen
sources:
  - https://github.com/jangraefen/hcloud-pricing-exporter
keywords:
  - hetzner
  - hcloud
  - prometheus
  - monitoring
  - prices
  - expenses

type: application

version: 0.3.0-r2
appVersion: 0.3.0

annotations:
  artifacthub.io/changes: |
    - Add more meta information to helm chart, so that it is better presented on artifacthub.io
