name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
      - .editorconfig
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ^1.15
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install golangci-lint
        run: |
          go get github.com/golangci/golangci-lint/cmd/golangci-lint
      - name: Run linters
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          golangci-lint run
  test:
    name: Test
    strategy:
      matrix:
        go-version: [ 1.15.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    needs: [ lint ]
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Run tests
        run: go test -v -race -covermode=atomic ./...

  build:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ^1.15
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Get dependencies
        run: |
          export GO111MODULE=on
          go get -v -t -d ./...
      - name: Build
        run: |
          export GO111MODULE=on
          GOOS=linux   GOARCH=amd64 go build -o bin/hcloud-pricing-exporter-linux-amd64       main.go
          GOOS=linux   GOARCH=arm64 go build -o bin/hcloud-pricing-exporter-linux-arm64       main.go
          GOOS=windows GOARCH=amd64 go build -o bin/hcloud-pricing-exporter-windows-amd64.exe main.go
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: binaries
          path: bin/
