name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
      - .editorconfig
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ^1.16
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install golangci-lint
        run: |
          go get github.com/golangci/golangci-lint/cmd/golangci-lint
      - name: Run linters
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go mod download
          golangci-lint run

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ^1.16
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Get dependencies
        run: |
          export GO111MODULE=on
          go get -v -t -d ./...
      - name: Build
        run: |
          export GO111MODULE=on
          go mod download
          GOOS=linux   GOARCH=amd64 go build -o bin/hcloud-pricing-exporter-linux-amd64       main.go
          GOOS=linux   GOARCH=arm64 go build -o bin/hcloud-pricing-exporter-linux-arm64       main.go
          GOOS=windows GOARCH=amd64 go build -o bin/hcloud-pricing-exporter-windows-amd64.exe main.go
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: binaries
          path: bin/
